/**
 * Structured GraphQL operation names organized by domain.
 * Use this for domain-specific operation lookups.
 */
export const OPERATIONS = {
  USER: {
    CREATE_USER: 'createUser',
    LOGIN_USER: 'loginUser',
    UPDATE_USER: 'updateUser',
    DELETE_USER_BY_ID: 'deleteUserById',
    DELETE_USER_BY_EMAIL: 'deleteUserByEmail',
    DELETE_USER_BY_USERNAME: 'deleteUserByUsername',
    READ_USER_BY_ID: 'readUserById',
    READ_USER_BY_EMAIL: 'readUserByEmail',
    READ_USER_BY_USERNAME: 'readUserByUsername',
    READ_USERS: 'readUsers',
    READ_BLOCKED_USERS: 'readBlockedUsers',
    READ_MUTED_USERS: 'readMutedUsers',
    READ_MUTED_ORGANIZATION_IDS: 'readMutedOrganizationIds',
    READ_SESSION_STATE: 'readSessionState',
    READ_ALL_SESSION_STATES: 'readAllSessionStates',
  },
  EVENT: {
    CREATE_EVENT: 'createEvent',
    UPDATE_EVENT: 'updateEvent',
    DELETE_EVENT: 'deleteEventById',
    DELETE_EVENT_BY_SLUG: 'deleteEventBySlug',
    READ_EVENT_BY_ID: 'readEventById',
    READ_EVENT_BY_SLUG: 'readEventBySlug',
    READ_EVENTS: 'readEvents',
    READ_TRENDING_EVENTS: 'readTrendingEvents',
  },
  EVENT_CATEGORY: {
    CREATE_EVENT_CATEGORY: 'createEventCategory',
    UPDATE_EVENT_CATEGORY: 'updateEventCategory',
    DELETE_EVENT_CATEGORY_BY_ID: 'deleteEventCategoryById',
    DELETE_EVENT_CATEGORY_BY_SLUG: 'deleteEventCategoryBySlug',
    READ_EVENT_CATEGORY_BY_ID: 'readEventCategoryById',
    READ_EVENT_CATEGORY_BY_SLUG: 'readEventCategoryBySlug',
    READ_EVENT_CATEGORIES: 'readEventCategories',
  },
  EVENT_CATEGORY_GROUP: {
    CREATE_EVENT_CATEGORY_GROUP: 'createEventCategoryGroup',
    UPDATE_EVENT_CATEGORY_GROUP: 'updateEventCategoryGroup',
    DELETE_EVENT_CATEGORY_GROUP_BY_SLUG: 'deleteEventCategoryGroupBySlug',
    READ_EVENT_CATEGORY_GROUP_BY_SLUG: 'readEventCategoryGroupBySlug',
    READ_EVENT_CATEGORY_GROUPS: 'readEventCategoryGroups',
  },
  EVENT_PARTICIPANT: {
    UPSERT_EVENT_PARTICIPANT: 'upsertEventParticipant',
    CANCEL_EVENT_PARTICIPANT: 'cancelEventParticipant',
    READ_EVENT_PARTICIPANTS: 'readEventParticipants',
  },
  ORGANIZATION: {
    CREATE_ORGANIZATION: 'createOrganization',
    UPDATE_ORGANIZATION: 'updateOrganization',
    DELETE_ORGANIZATION: 'deleteOrganizationById',
    READ_ORGANIZATION_BY_ID: 'readOrganizationById',
    READ_ORGANIZATION_BY_SLUG: 'readOrganizationBySlug',
    READ_ORGANIZATIONS: 'readOrganizations',
  },
  ORGANIZATION_MEMBERSHIP: {
    CREATE_ORGANIZATION_MEMBERSHIP: 'createOrganizationMembership',
    UPDATE_ORGANIZATION_MEMBERSHIP: 'updateOrganizationMembership',
    DELETE_ORGANIZATION_MEMBERSHIP: 'deleteOrganizationMembership',
    READ_ORGANIZATION_MEMBERSHIP_BY_ID: 'readOrganizationMembershipById',
    READ_ORGANIZATION_MEMBERSHIPS_BY_ORG_ID: 'readOrganizationMembershipsByOrgId',
  },
  VENUE: {
    CREATE_VENUE: 'createVenue',
    UPDATE_VENUE: 'updateVenue',
    DELETE_VENUE: 'deleteVenueById',
    READ_VENUE_BY_ID: 'readVenueById',
    READ_VENUE_BY_SLUG: 'readVenueBySlug',
    READ_VENUES: 'readVenues',
    READ_VENUES_BY_ORG_ID: 'readVenuesByOrgId',
  },
  FOLLOW: {
    FOLLOW: 'follow',
    UNFOLLOW: 'unfollow',
    ACCEPT_FOLLOW_REQUEST: 'acceptFollowRequest',
    REJECT_FOLLOW_REQUEST: 'rejectFollowRequest',
    REMOVE_FOLLOWER: 'removeFollower',
    READ_FOLLOWING: 'readFollowing',
    READ_PENDING_FOLLOW_REQUESTS: 'readPendingFollowRequests',
    READ_FOLLOW_REQUESTS: 'readFollowRequests',
    READ_FOLLOWERS: 'readFollowers',
    READ_SAVED_EVENTS: 'readSavedEvents',
  },
  ACTIVITY: {
    LOG_ACTIVITY: 'logActivity',
    READ_ACTIVITIES_BY_ACTOR: 'readActivitiesByActor',
    READ_FEED: 'readFeed',
  },
  NOTIFICATION: {
    MARK_NOTIFICATION_READ: 'markNotificationRead',
    MARK_ALL_NOTIFICATIONS_READ: 'markAllNotificationsRead',
    DELETE_NOTIFICATION: 'deleteNotification',
    READ_NOTIFICATIONS: 'readNotifications',
  },
  EVENT_MOMENT: {
    CREATE_EVENT_MOMENT: 'createEventMoment',
    DELETE_EVENT_MOMENT: 'deleteEventMoment',
    READ_EVENT_MOMENTS: 'readEventMoments',
    READ_USER_EVENT_MOMENTS: 'readUserEventMoments',
    READ_FOLLOWED_MOMENTS: 'readFollowedMoments',
  },
  MEDIA: {
    GET_MEDIA_UPLOAD_URL: 'getMediaUploadUrl',
    GET_EVENT_MOMENT_UPLOAD_URL: 'getEventMomentUploadUrl',
  },
  ADMIN: {
    READ_ADMIN_DASHBOARD_STATS: 'readAdminDashboardStats',
  },
} as const;
