import { APPLICATION_STAGES } from '@gatherle/commons';

export const DEFAULT_GRAPHQL_API_THROTTLE_RATE_LIMITS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 50,
  [APPLICATION_STAGES.BETA]: 25,
  [APPLICATION_STAGES.GAMMA]: 100,
  [APPLICATION_STAGES.PROD]: 250,
};

export const DEFAULT_GRAPHQL_API_THROTTLE_BURST_LIMITS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 100,
  [APPLICATION_STAGES.BETA]: 50,
  [APPLICATION_STAGES.GAMMA]: 200,
  [APPLICATION_STAGES.PROD]: 500,
};

export const DEFAULT_GRAPHQL_API_WAF_RATE_LIMITS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 2000,
  [APPLICATION_STAGES.BETA]: 1000,
  [APPLICATION_STAGES.GAMMA]: 3000,
  [APPLICATION_STAGES.PROD]: 10000,
};
