import { APPLICATION_STAGES } from '@gatherle/commons';

export const DEFAULT_GRAPHQL_API_CLIENT_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 40,
  [APPLICATION_STAGES.BETA]: 20,
  [APPLICATION_STAGES.GAMMA]: 40,
  [APPLICATION_STAGES.PROD]: 100,
};

export const DEFAULT_GRAPHQL_API_SERVER_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 5,
  [APPLICATION_STAGES.BETA]: 5,
  [APPLICATION_STAGES.GAMMA]: 10,
  [APPLICATION_STAGES.PROD]: 20,
};

export const DEFAULT_GRAPHQL_API_THROTTLE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 1,
  [APPLICATION_STAGES.BETA]: 1,
  [APPLICATION_STAGES.GAMMA]: 2,
  [APPLICATION_STAGES.PROD]: 5,
};

export const DEFAULT_GRAPHQL_QUERY_GUARD_REJECTION_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 10,
  [APPLICATION_STAGES.BETA]: 8,
  [APPLICATION_STAGES.GAMMA]: 12,
  [APPLICATION_STAGES.PROD]: 20,
};

export const DEFAULT_AUTH_FAILURE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 10,
  [APPLICATION_STAGES.BETA]: 8,
  [APPLICATION_STAGES.GAMMA]: 15,
  [APPLICATION_STAGES.PROD]: 30,
};

export const DEFAULT_AUTH_LOCKOUT_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 2,
  [APPLICATION_STAGES.BETA]: 2,
  [APPLICATION_STAGES.GAMMA]: 3,
  [APPLICATION_STAGES.PROD]: 5,
};

export const DEFAULT_WEBSOCKET_CLIENT_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 20,
  [APPLICATION_STAGES.BETA]: 12,
  [APPLICATION_STAGES.GAMMA]: 20,
  [APPLICATION_STAGES.PROD]: 50,
};

export const DEFAULT_WEBSOCKET_INTEGRATION_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 1,
  [APPLICATION_STAGES.BETA]: 1,
  [APPLICATION_STAGES.GAMMA]: 2,
  [APPLICATION_STAGES.PROD]: 5,
};

export const DEFAULT_WEBSOCKET_EXECUTION_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 1,
  [APPLICATION_STAGES.BETA]: 1,
  [APPLICATION_STAGES.GAMMA]: 2,
  [APPLICATION_STAGES.PROD]: 5,
};

export const DEFAULT_WEBSOCKET_LAMBDA_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 1,
  [APPLICATION_STAGES.BETA]: 1,
  [APPLICATION_STAGES.GAMMA]: 2,
  [APPLICATION_STAGES.PROD]: 5,
};

export const DEFAULT_WEBSOCKET_LAMBDA_THROTTLE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 1,
  [APPLICATION_STAGES.BETA]: 1,
  [APPLICATION_STAGES.GAMMA]: 1,
  [APPLICATION_STAGES.PROD]: 3,
};

export const DEFAULT_WEBSOCKET_CONNECT_SPIKE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 40,
  [APPLICATION_STAGES.BETA]: 20,
  [APPLICATION_STAGES.GAMMA]: 40,
  [APPLICATION_STAGES.PROD]: 120,
};

export const DEFAULT_WEBSOCKET_MESSAGE_SPIKE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 150,
  [APPLICATION_STAGES.BETA]: 60,
  [APPLICATION_STAGES.GAMMA]: 120,
  [APPLICATION_STAGES.PROD]: 400,
};
