import { APPLICATION_STAGES } from '@gatherle/commons';

// These thresholds are tuned for sustained operator-relevant spikes rather than
// every ordinary 4xx/auth/query-guard blip. The corresponding alarms now use
// multi-period evaluation, so these values are intentionally higher than the
// previous single-datapoint defaults.
export const DEFAULT_GRAPHQL_API_CLIENT_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 100,
  [APPLICATION_STAGES.BETA]: 150,
  [APPLICATION_STAGES.GAMMA]: 180,
  [APPLICATION_STAGES.PROD]: 300,
};

export const DEFAULT_GRAPHQL_API_SERVER_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 10,
  [APPLICATION_STAGES.BETA]: 10,
  [APPLICATION_STAGES.GAMMA]: 15,
  [APPLICATION_STAGES.PROD]: 30,
};

export const DEFAULT_GRAPHQL_API_THROTTLE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 3,
  [APPLICATION_STAGES.BETA]: 3,
  [APPLICATION_STAGES.GAMMA]: 5,
  [APPLICATION_STAGES.PROD]: 10,
};

export const DEFAULT_GRAPHQL_QUERY_GUARD_REJECTION_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 20,
  [APPLICATION_STAGES.BETA]: 20,
  [APPLICATION_STAGES.GAMMA]: 30,
  [APPLICATION_STAGES.PROD]: 60,
};

export const DEFAULT_AUTH_FAILURE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 20,
  [APPLICATION_STAGES.BETA]: 25,
  [APPLICATION_STAGES.GAMMA]: 35,
  [APPLICATION_STAGES.PROD]: 60,
};

export const DEFAULT_AUTH_LOCKOUT_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 4,
  [APPLICATION_STAGES.BETA]: 5,
  [APPLICATION_STAGES.GAMMA]: 6,
  [APPLICATION_STAGES.PROD]: 10,
};

export const DEFAULT_OCCURRENCE_MISSING_SERIES_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 10,
  [APPLICATION_STAGES.BETA]: 10,
  [APPLICATION_STAGES.GAMMA]: 15,
  [APPLICATION_STAGES.PROD]: 20,
};

export const DEFAULT_OCCURRENCE_LOW_HORIZON_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 10,
  [APPLICATION_STAGES.BETA]: 10,
  [APPLICATION_STAGES.GAMMA]: 15,
  [APPLICATION_STAGES.PROD]: 20,
};

export const DEFAULT_OCCURRENCE_DRIFT_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 25,
  [APPLICATION_STAGES.BETA]: 25,
  [APPLICATION_STAGES.GAMMA]: 35,
  [APPLICATION_STAGES.PROD]: 50,
};

export const DEFAULT_WEBSOCKET_CLIENT_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 40,
  [APPLICATION_STAGES.BETA]: 40,
  [APPLICATION_STAGES.GAMMA]: 60,
  [APPLICATION_STAGES.PROD]: 120,
};

export const DEFAULT_WEBSOCKET_INTEGRATION_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 3,
  [APPLICATION_STAGES.BETA]: 3,
  [APPLICATION_STAGES.GAMMA]: 5,
  [APPLICATION_STAGES.PROD]: 10,
};

export const DEFAULT_WEBSOCKET_EXECUTION_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 15,
  [APPLICATION_STAGES.BETA]: 15,
  [APPLICATION_STAGES.GAMMA]: 20,
  [APPLICATION_STAGES.PROD]: 40,
};

export const DEFAULT_WEBSOCKET_LAMBDA_ERROR_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 3,
  [APPLICATION_STAGES.BETA]: 3,
  [APPLICATION_STAGES.GAMMA]: 5,
  [APPLICATION_STAGES.PROD]: 10,
};

export const DEFAULT_WEBSOCKET_LAMBDA_THROTTLE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 2,
  [APPLICATION_STAGES.BETA]: 2,
  [APPLICATION_STAGES.GAMMA]: 3,
  [APPLICATION_STAGES.PROD]: 5,
};

export const DEFAULT_WEBSOCKET_CONNECT_SPIKE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 100,
  [APPLICATION_STAGES.BETA]: 100,
  [APPLICATION_STAGES.GAMMA]: 150,
  [APPLICATION_STAGES.PROD]: 300,
};

export const DEFAULT_WEBSOCKET_MESSAGE_SPIKE_ALARM_THRESHOLDS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 250,
  [APPLICATION_STAGES.BETA]: 250,
  [APPLICATION_STAGES.GAMMA]: 350,
  [APPLICATION_STAGES.PROD]: 800,
};
