import { APPLICATION_STAGES } from '@gatherle/commons';

export const DEFAULT_WEBSOCKET_STAGE_THROTTLE_RATE_LIMITS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 25,
  [APPLICATION_STAGES.BETA]: 12,
  [APPLICATION_STAGES.GAMMA]: 20,
  [APPLICATION_STAGES.PROD]: 40,
};

export const DEFAULT_WEBSOCKET_STAGE_THROTTLE_BURST_LIMITS: Record<string, number> = {
  [APPLICATION_STAGES.DEV]: 50,
  [APPLICATION_STAGES.BETA]: 24,
  [APPLICATION_STAGES.GAMMA]: 40,
  [APPLICATION_STAGES.PROD]: 80,
};
