const HOURS_TO_MS = 60 * 60 * 1000;

export const EVENT_MOMENT_EXPIRY_HOURS: number = 24 * 30;
export const EVENT_MOMENT_EXPIRY_MS = EVENT_MOMENT_EXPIRY_HOURS * HOURS_TO_MS;
export const EVENT_MOMENT_EXPIRY_LABEL = `${EVENT_MOMENT_EXPIRY_HOURS} hour${EVENT_MOMENT_EXPIRY_HOURS === 1 ? '' : 's'}`;
