const config = {
  preset: 'jest-expo',
  rootDir: '../../',
  setupFilesAfterEnv: ['<rootDir>/test/unit/setup.ts'],
  testMatch: ['<rootDir>/test/unit/**/*.test.[jt]s?(x)'],
  testPathIgnorePatterns: ['<rootDir>/dist/', '<rootDir>/node_modules/'],
  testTimeout: 10000,
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@data/(.*)$': '<rootDir>/data/$1',
    '^@gatherle/commons$': '<rootDir>/../../packages/commons/lib/index.ts',
    '^@gatherle/commons/(.*)$': '<rootDir>/../../packages/commons/lib/$1',
    '^react$': '<rootDir>/node_modules/react',
    '^react/jsx-runtime$': '<rootDir>/node_modules/react/jsx-runtime',
    '^react/jsx-dev-runtime$': '<rootDir>/node_modules/react/jsx-dev-runtime',
    '^react-dom$': '<rootDir>/node_modules/react-dom',
    '^react-test-renderer$': '<rootDir>/node_modules/react-test-renderer',
    '^react-native$': '<rootDir>/node_modules/react-native',
    '^react-native/(.*)$': '<rootDir>/node_modules/react-native/$1',
  },
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?|expo|expo-.*|@expo/.*|@expo-google-fonts/.*|@react-navigation/.*|@gorhom/.*|react-native-reanimated|react-native-gesture-handler|react-native-safe-area-context|react-native-screens)/)',
  ],
  collectCoverage: true,
  coverageDirectory: '<rootDir>/test/unit/coverage',
  coverageReporters: ['text', 'text-summary', 'lcov'],
  collectCoverageFrom: [
    '<rootDir>/src/lib/account/forms.ts',
    '<rootDir>/src/lib/account/profileBadges.ts',
    '<rootDir>/src/lib/auth.ts',
    '<rootDir>/src/lib/auth/**/*.ts',
    '<rootDir>/src/lib/events/adapters.ts',
    '<rootDir>/src/lib/events/formatters.ts',
    '<rootDir>/src/lib/messages/chatRealtimeProtocol.ts',
    '<rootDir>/src/lib/messages/thread.ts',
    '<rootDir>/src/lib/realtime/subscriberStore.ts',
    '<rootDir>/src/lib/venues/forms.ts',
    '<rootDir>/src/components/core/InlineButton.tsx',
    '<rootDir>/src/components/core/FilterActionButton.tsx',
    '<rootDir>/src/components/core/FilterChip.tsx',
    '<rootDir>/src/components/core/ProfileAvatar.tsx',
    '<rootDir>/src/components/core/SmallActionButton.tsx',
    '<rootDir>/src/components/core/StateNotice.tsx',
    '<rootDir>/src/components/account/shared/AccountChoiceChip.tsx',
    '<rootDir>/src/components/community/CommunityMemberRow.tsx',
    '<rootDir>/src/components/venues/VenueListItem.tsx',
    '<rootDir>/src/hooks/core/useKeyboardAwareField.ts',
    '<rootDir>/src/hooks/core/usePullToRefresh.ts',
    '!<rootDir>/**/*.d.ts',
    '!<rootDir>/**/index.ts',
  ],
  coveragePathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/test/'],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
};

module.exports = config;
