import {Gender, IUser, UserType} from '../../interface/users';

const users: IUser[] = [
    {
        _id: 'mongodbUser001',
        userID: 'user001',
        email: 'user001@gmail.com',
        username: 'jackBaur',
        address: 'KZN, Durban, 8000',
        birthdate: 'a birth date',
        family_name: 'Baur',
        gender: Gender.MALE,
        given_name: 'Jack',
        encrypted_password: 'dfuyihjknbsndhj',
        phone_number: '',
        profile_picture: '',
        userType: UserType.USER,
    },
    {
        _id: 'mongodbUser002',
        userID: 'host001',
        email: 'jay@rocknation.com',
        username: 'jayz',
        address: 'USA, Brooklyn, 8000',
        birthdate: 'a birth date',
        family_name: 'Carter',
        gender: Gender.MALE,
        given_name: 'Sean',
        encrypted_password: 'tryuik',
        phone_number: '',
        profile_picture: '',
        userType: UserType.HOST,
    },
    {
        _id: 'mongodbUser003',
        userID: 'user002',
        email: 'celin@yahoo.com',
        username: 'celin352',
        address: 'WC, Parklands, 8000',
        birthdate: 'a birth date',
        family_name: 'Maluleke',
        gender: Gender.FEMALE,
        given_name: 'Celin',
        encrypted_password: 'wreiujk22',
        phone_number: '',
        profile_picture: '',
        userType: UserType.USER,
    },
    {
        _id: 'mongodbUser004',
        userID: 'host002',
        email: 'Jeff@amazon.com',
        username: 'jeffbez',
        address: 'USA, Seattle, 8000',
        birthdate: 'a birth date',
        family_name: 'Bezos',
        gender: Gender.MALE,
        given_name: 'Jeff',
        encrypted_password: 'sdjhjkj34',
        phone_number: '',
        profile_picture: '',
        userType: UserType.ADMIN,
    },
];

export default users;
