import {UserRole, Gender, UserType, CreateUserInputType} from '../../graphql/types';

const users: CreateUserInputType[] = [
    {
        // id: 'user001',
        email: 'user001@gmail.com',
        username: 'jackBaur',
        address: 'KZN, Durban, 8000',
        birthdate: 'a birth date',
        family_name: 'Baur',
        gender: Gender.MALE,
        given_name: 'Jack',
        password: 'dfuyihjknbsndhj',
        phone_number: '',
        profile_picture: '',
        userType: UserRole.USER,
    },
    {
        // id: 'host001',
        email: 'jay@rocknation.com',
        username: 'jayz',
        address: 'USA, Brooklyn, 8000',
        birthdate: 'a birth date',
        family_name: 'Carter',
        gender: Gender.MALE,
        given_name: 'Sean',
        password: 'tryuik',
        phone_number: '',
        profile_picture: '',
        userType: UserRole.HOST,
    },
    {
        // id: 'user002',
        email: 'celin@yahoo.com',
        username: 'celin352',
        address: 'WC, Parklands, 8000',
        birthdate: 'a birth date',
        family_name: 'Maluleke',
        gender: Gender.FEMALE,
        given_name: 'Celin',
        password: 'wreiujk22',
        phone_number: '',
        profile_picture: '',
        userType: UserRole.USER,
    },
    {
        // id: 'host002',
        email: 'Jeff@amazon.com',
        username: 'jeffbez',
        address: 'USA, Seattle, 8000',
        birthdate: 'a birth date',
        family_name: 'Bezos',
        gender: Gender.MALE,
        given_name: 'Jeff',
        password: 'sdjhjkj34',
        phone_number: '',
        profile_picture: '',
        userType: UserRole.ADMIN,
    },
];

export default users;
