import 'reflect-metadata';
import { Field, ID, InputType, ObjectType, registerEnumType } from 'type-graphql';
import { index, modelOptions, prop } from '@typegoose/typegoose';
import { User } from './user';
import { Event } from './event';

export enum EventMomentType {
  Text = 'text',
  Image = 'image',
  Video = 'video',
}

export enum EventMomentState {
  Processing = 'Processing',
  Ready = 'Ready',
  Failed = 'Failed',
}

registerEnumType(EventMomentType, {
  name: 'EventMomentType',
  description: 'The media type of an event moment post',
});

registerEnumType(EventMomentState, {
  name: 'EventMomentState',
  description: 'Processing lifecycle state of an event moment (relevant for video transcoding)',
});

@ObjectType('EventMoment', { description: 'An ephemeral moment post linked to an event, expires after 24 hours' })
@modelOptions({ schemaOptions: { timestamps: true } })
@index({ eventId: 1, authorId: 1 })
@index({ authorId: 1, createdAt: -1 })
@index({ expiresAt: 1 }, { expireAfterSeconds: 0 })
export class EventMoment {
  @prop({ required: true, unique: true, index: true, type: () => String })
  @Field(() => ID)
  momentId: string;

  @prop({ required: true, type: () => String })
  @Field(() => ID)
  eventId: string;

  @prop({ required: true, type: () => String })
  @Field(() => ID)
  authorId: string;

  @prop({ required: true, enum: EventMomentType, type: () => String })
  @Field(() => EventMomentType)
  type: EventMomentType;

  @prop({ type: () => String })
  @Field(() => String, {
    nullable: true,
    description: 'Text body for type=Text; optional caption for image and video moments',
  })
  caption?: string;

  @prop({ type: () => String })
  @Field(() => String, {
    nullable: true,
    description: 'CloudFront URL for image moments; HLS .m3u8 URL for video moments',
  })
  mediaUrl?: string;

  @prop({ type: () => String })
  @Field(() => String, {
    nullable: true,
    description: 'CloudFront URL for the video poster frame (generated by MediaConvert)',
  })
  thumbnailUrl?: string;

  @prop({ type: () => String })
  @Field(() => String, {
    nullable: true,
    description: 'Background colour token for text moments (e.g. "bg-purple-600")',
  })
  background?: string;

  @prop({ enum: EventMomentState, default: EventMomentState.Ready, type: () => String })
  @Field(() => EventMomentState)
  state: EventMomentState;

  @prop({ type: () => Number })
  @Field(() => Number, { nullable: true, description: 'Duration in seconds for video moments' })
  durationSeconds?: number;

  @prop({ required: true, type: () => Date })
  @Field(() => Date, { description: 'When this moment expires and is automatically deleted (createdAt + 24h)' })
  expiresAt: Date;

  @prop({ type: () => Date })
  @Field(() => Date)
  createdAt: Date;

  // GraphQL-only field resolved via @FieldResolver
  @Field(() => User, { nullable: true })
  author?: User;

  // GraphQL-only field resolved via @FieldResolver
  @Field(() => Event, { nullable: true })
  event?: Event;
}

@ObjectType('EventMomentPage', { description: 'Paginated list of event moments' })
export class EventMomentPage {
  @Field(() => [EventMoment])
  items: EventMoment[];

  @Field(() => String, { nullable: true })
  nextCursor?: string;

  @Field(() => Boolean)
  hasMore: boolean;
}

@InputType('CreateEventMomentInput')
export class CreateEventMomentInput {
  @Field(() => ID)
  eventId: string;

  @Field(() => EventMomentType)
  type: EventMomentType;

  @Field(() => String, {
    nullable: true,
    description: 'Text body (required when type=Text); optional caption otherwise',
  })
  caption?: string;

  @Field(() => String, {
    nullable: true,
    description: 'S3 key from getEventMomentUploadUrl (required for image and video moments)',
  })
  mediaKey?: string;

  @Field(() => String, {
    nullable: true,
    description: 'S3 key for the video poster frame, generated client-side and uploaded before creating the moment',
  })
  thumbnailKey?: string;

  @Field(() => String, {
    nullable: true,
    description: 'Background colour token for text moments (e.g. "bg-purple-600")',
  })
  background?: string;
}
