import 'reflect-metadata';
import { Field, ID, InputType, ObjectType, registerEnumType } from 'type-graphql';
import { index, modelOptions, prop, Severity } from '@typegoose/typegoose';
import { User } from './user';

export enum MobileDeviceAccessPlatform {
  Android = 'Android',
  Ios = 'Ios',
}

export enum MobileDeviceAccessStatus {
  Pending = 'Pending',
  Approved = 'Approved',
  Blocked = 'Blocked',
}

registerEnumType(MobileDeviceAccessPlatform, {
  name: 'MobileDeviceAccessPlatform',
  description: 'Native mobile platform that registered the device installation.',
});

registerEnumType(MobileDeviceAccessStatus, {
  name: 'MobileDeviceAccessStatus',
  description: 'Whether a mobile device installation can use the native app.',
});

@ObjectType('MobileDeviceAccess', {
  description: 'Access record used to track and control whether a specific native app installation can use Gatherle.',
})
@modelOptions({ schemaOptions: { timestamps: true }, options: { allowMixed: Severity.ALLOW } })
@index({ deviceInstallationId: 1 }, { unique: true })
@index({ status: 1, lastSeenAt: -1 })
export class MobileDeviceAccess {
  @prop({ required: true, index: true, type: () => String })
  @Field(() => ID, { description: 'Unique identifier for this mobile device access record.' })
  mobileDeviceAccessId: string;

  @prop({ required: true, index: true, type: () => String })
  @Field(() => String, { description: 'Stable app-install identifier generated by the native client.' })
  deviceInstallationId: string;

  @prop({ required: true, enum: MobileDeviceAccessPlatform, type: () => String })
  @Field(() => MobileDeviceAccessPlatform, { description: 'Native platform that owns this app installation.' })
  platform: MobileDeviceAccessPlatform;

  @prop({
    required: true,
    enum: MobileDeviceAccessStatus,
    type: () => String,
    default: MobileDeviceAccessStatus.Approved,
  })
  @Field(() => MobileDeviceAccessStatus, {
    description: 'Current access state for this mobile app installation.',
  })
  status: MobileDeviceAccessStatus;

  @prop({ type: () => String })
  @Field(() => String, { nullable: true, description: 'Human-readable app version reported by the client.' })
  appVersion?: string;

  @prop({ type: () => String })
  @Field(() => String, { nullable: true, description: 'Platform-native build version reported by the client.' })
  buildVersion?: string;

  @prop({ type: () => String })
  registrationSecret?: string;

  @prop({ type: () => Date, default: () => new Date() })
  @Field(() => Date, { description: 'When this installation first contacted the API.' })
  firstSeenAt: Date;

  @prop({ type: () => Date, default: () => new Date() })
  @Field(() => Date, { description: 'When this installation most recently contacted the API.' })
  lastSeenAt: Date;

  @prop({ type: () => [String], default: [] })
  @Field(() => [String], {
    nullable: true,
    description: 'Distinct signed-in user IDs observed on this installation.',
  })
  seenUserIds?: string[];

  @prop({ type: () => String })
  @Field(() => String, {
    nullable: true,
    description: 'Most recent signed-in user ID observed on this installation.',
  })
  lastSeenUserId?: string;

  @prop({ type: () => Date })
  @Field(() => Date, {
    nullable: true,
    description: 'When a signed-in account last used this installation.',
  })
  lastAuthenticatedAt?: Date;

  @prop({ type: () => Date })
  @Field(() => Date, { nullable: true, description: 'When an admin last reviewed this installation.' })
  reviewedAt?: Date;

  @prop({ type: () => String })
  @Field(() => String, {
    nullable: true,
    description: 'Admin user ID that last changed this installation status.',
  })
  reviewedByUserId?: string;

  @Field(() => User, {
    nullable: true,
    description: 'Most recent signed-in user observed on this installation.',
  })
  lastSeenUser?: User;

  @Field(() => [User], {
    nullable: true,
    description: 'Distinct signed-in users observed on this installation.',
  })
  seenUsers?: User[];

  @Field(() => Date, { description: 'When this access record was created.' })
  createdAt: Date;

  @Field(() => Date, { description: 'When this access record was last updated.' })
  updatedAt?: Date;
}

@InputType('RegisterMobileDeviceAccessInput', {
  description: 'Input used by the native app to register or refresh a device installation.',
})
export class RegisterMobileDeviceAccessInput {
  @Field(() => String, { description: 'Stable app-install identifier generated by the native client.' })
  deviceInstallationId: string;

  @Field(() => MobileDeviceAccessPlatform, { description: 'Native platform that owns this app installation.' })
  platform: MobileDeviceAccessPlatform;

  @Field(() => String, { nullable: true, description: 'Human-readable app version reported by the client.' })
  appVersion?: string;

  @Field(() => String, { nullable: true, description: 'Platform-native build version reported by the client.' })
  buildVersion?: string;

  @Field(() => String, {
    nullable: true,
    description: 'Opaque per-install secret returned after first registration and required for future heartbeats.',
  })
  registrationSecret?: string;
}

@ObjectType('MobileDeviceAccessRegistrationResult', {
  description: 'Public-safe registration result returned to a native installation during access checks.',
})
export class MobileDeviceAccessRegistrationResult {
  @Field(() => String, { description: 'Stable app-install identifier generated by the native client.' })
  deviceInstallationId: string;

  @Field(() => MobileDeviceAccessPlatform, { description: 'Native platform that owns this app installation.' })
  platform: MobileDeviceAccessPlatform;

  @Field(() => MobileDeviceAccessStatus, { description: 'Current access state for this app installation.' })
  status: MobileDeviceAccessStatus;

  @Field(() => String, { nullable: true, description: 'Human-readable app version reported by the client.' })
  appVersion?: string;

  @Field(() => String, { nullable: true, description: 'Platform-native build version reported by the client.' })
  buildVersion?: string;

  @Field(() => String, {
    nullable: true,
    description: 'Opaque per-install secret returned after first registration and reused for future heartbeats.',
  })
  registrationSecret?: string;
}

@InputType('ReadMobileDeviceAccessesInput', {
  description: 'Optional filters used by admins to inspect mobile device access records.',
})
export class ReadMobileDeviceAccessesInput {
  @Field(() => MobileDeviceAccessStatus, {
    nullable: true,
    description: 'Optional status filter for the returned device access records.',
  })
  status?: MobileDeviceAccessStatus;

  @Field(() => String, {
    nullable: true,
    description: 'Optional text search against device installation IDs and version metadata.',
  })
  search?: string;
}

@InputType('UpdateMobileDeviceAccessStatusInput', {
  description: 'Input used by admins to update the access state for a specific mobile app installation.',
})
export class UpdateMobileDeviceAccessStatusInput {
  @Field(() => String, { description: 'Stable app-install identifier generated by the native client.' })
  deviceInstallationId: string;

  @Field(() => MobileDeviceAccessStatus, { description: 'Access state to apply to this app installation.' })
  status: MobileDeviceAccessStatus;
}
